### PR TITLE
Cpu matmul with multi-threading

### PR DESCRIPTION
**Pull request by chengchingwen**
Adapting the multi-threading strategy used in [NNlib.batched_gemm!](https://github.com/FluxML/NNlib.jl/blob/cd3851d31e95020e77e67f80fb6402b5b87db1e6/src/gemm.jl#L91-L139) for cpu matmul. 

cc: @theabhirath

### CODE REVIEW

**Comment by theabhirath** [comment]
Wow, this is great! I'll try and put together a benchmark run by the weekend - an initial trial just now didn't yield very good results but maybe I'm missing something. This should definitely help in theory though

**Comment by chengchingwen** [comment]
Apparently the computer don't like the way I write the loop. The new commit should give identical results.

**Comment by theabhirath** [comment]
> Apparently the computer don't like the way I write the loop. The new commit should give identical results.

I tried it, and it's still off by the pace by about a second for the full `ViT(:base)` forward pass. For reference, the original MHAttention implementation from Metalhead is [here](https://github.com/FluxML/Metalhead.jl/blob/88bcacb81b643066adecdc9bb108a6dbcaad9e3c/src/layers/attention.jl#L32-L50). This one is:

```julia
function (m::MHAttention)(x)
    q, k, v = chunk(m.qkvlayer(x), 3; dims = 1)
    @cast q[h, b, d, n] := q[(h, d), n, b] h in 1:m.heads
    @cast k[h, b, d, n] := k[(h, d), n, b] h in 1:m.heads
    @cast v[h, b, d, n] := v[(h, d), n, b] h in 1:m.heads
    dots = NeuralAttentionlib.matmul(q, permutedims(k, (2, 1, 3, 4)), m.scale)
    attn = softmax(dots; dims = 3)
    # PS - this is significantly slower than the one below because `unwrap_collapse` takes a lot of time
    # out = NeuralAttentionlib.unwrap_collapse(NeuralAttentionlib.matmul(attn, v))
    # @cast out[(h, d), n, b] := out[h, b, d, n] in 1:m.heads
    out = NeuralAttentionlib.matmul(attn, v)
    out = reshape(out, :, size(q, 4), size(q, 2))
    m.outlayer(out)
end
```

I checked with native `reshape` instead of TensorCast and the timings are unchanged, so that doesn't seem to be the blocker. So the `matmul` operation is still slower

**Comment by theabhirath** [comment]
PS: allocations are also a worry. For the NeuralAttentionlib version:

```julia
julia> @benchmark model($x)
BenchmarkTools.Trial: 3 samples with 1 evaluation.
 Range (min … max):  1.776 s …   1.880 s  ┊ GC (min … max): 22.43% … 22.62%
 Time  (median):     1.814 s              ┊ GC (median):    21.96%
 Time  (mean ± σ):   1.824 s ± 52.251 ms  ┊ GC (mean ± σ):  22.29% ±  0.42%

  █                   █                                   █  
  █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█ ▁
  1.78 s         Histogram: frequency by time        1.88 s <

 Memory estimate: 8.75 GiB, allocs estimate: 2765560.
```

vs for the Metalhead version right now:

```julia
julia> @benchmark model($x)
BenchmarkTools.Trial: 7 samples with 1 evaluation.
 Range (min … max):  721.637 ms … 777.299 ms  ┊ GC (min … max): 3.08% … 3.14%
 Time  (median):     746.597 ms               ┊ GC (median):    2.98%
 Time  (mean ± σ):   750.055 ms ±  20.459 ms  ┊ GC (mean ± σ):  2.91% ± 0.56%

  █        █               █ █           █               █    █
  █▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁█▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁█ ▁
  722 ms           Histogram: frequency by time          777 ms <

 Memory estimate: 808.90 MiB, allocs estimate: 2706.
```

**Comment by chengchingwen** [comment]
@theabhirath Could you give a small script that I can directly run and reproduce the result? 

I'm guessing there might be some type stability issue since `unwrap_collapse` is either `identity` or `parent` which really shouldn't cause performance issue.

**Comment by theabhirath** [comment]
This is off the Metalhead master branch, vs this branch: https://github.com/FluxML/Metalhead.jl/tree/a2/attn-test. The latter uses the stable version of TensorCast but the version of NeuralAttentionlib on this branch.

```julia
using Metalhead
using BenchmarkTools

model = ViT(:base)
x = rand(Float32, 256, 256, 3, 2)

@benchmark model($x)
```

My timings were on Julia v1.8.2 with an M1 Mac

**Comment by theabhirath** [comment]
AFAIK TensorCast lowers to native `reshape` behind the scenes, and I checked without it and it didn't appear to cause any slowdowns. I'll try to profile the code, see which lines are behind the slowdown

**Comment by theabhirath** [comment]
@chengchingwen So I ran a couple more benchmarks. There was a bug in the Metalhead code, but after correcting that, the timing difference is now down to 200 ms. The code is 

```julia
function (m::MHAttention)(x::AbstractArray{T, 3}) where {T}
    q, k, v = chunk(m.qkv_layer(x), 3; dims = 1)
    # Alternative TensorCast use for einops-like reshaping
    # @cast q[d, n, h, b] := q[(h, d), n, b] h in 1:m.nheads
    # @cast k[d, n, h, b] := k[(h, d), n, b] h in 1:m.nheads
    # @cast v[d, n, h, b] := v[(h, d), n, b] h in 1:m.nheads
    q = reshape(q, size(q, 1) ÷ m.nheads, size(q, 2), m.nheads, size(q, 3))
    k = reshape(k, size(k, 1) ÷ m.nheads, size(k, 2), m.nheads, size(k, 3))
    v = reshape(v, size(v, 1) ÷ m.nheads, size(v, 2), m.nheads, size(v, 3))
    scale = convert(T, sqrt(size(q, 1) / m.nheads))
    dots = NeuralAttentionlib.matmul(q, permutedims(k, (2, 1, 3, 4)), scale)
    attn = m.attn_drop(softmax(dots; dims = 3))
    # this is significantly slower than the one below because `unwrap_collapse` takes a lot of time
    # out = NeuralAttentionlib.unwrap_collapse(NeuralAttentionlib.matmul(attn, v))
    # @cast out[(h, d), n, b] := out[d, n, h, b] in 1:m.nheads
    out = NeuralAttentionlib.matmul(attn, v)
    return m.projection(reshape(out, :, size(q, 2), size(q, 4)))
end
```

This gives

```julia
julia> @benchmark model($x)
BenchmarkTools.Trial: 7 samples with 1 evaluation.
 Range (min … max):  757.414 ms … 762.811 ms  ┊ GC (min … max): 1.16% … 1.33%
 Time  (median):     760.716 ms               ┊ GC (median):    1.25%
 Time  (mean ± σ):   760.436 ms ±   2.277 ms  ┊ GC (mean ± σ):  1.24% ± 0.10%

  █   █                 █              █                █   █ █  
  █▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁█▁█ ▁
  757 ms           Histogram: frequency by time          763 ms <

 Memory estimate: 530.13 MiB, allocs estimate: 6700.
```

With TensorCast instead of native reshapes:

```julia
BenchmarkTools.Trial: 6 samples with 1 evaluation.
 Range (min … max):  876.181 ms … 887.042 ms  ┊ GC (min … max): 1.00% … 1.56%
 Time  (median):     877.206 ms               ┊ GC (median):    1.07%
 Time  (mean ± σ):   878.870 ms ±   4.150 ms  ┊ GC (mean ± σ):  1.15% ± 0.26%

  ███      █      █                                           █  
  ███▁▁▁▁▁▁█▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█ ▁
  876 ms           Histogram: frequency by time          887 ms <

 Memory estimate: 530.19 MiB, allocs estimate: 6916.
```

So TensorCast causes a roughly 100 ms slowdown. Not sure if this is expected, but possibly the reshape the macro lowers to is less efficient than the one-liner? `unwrap_collapse` is still slow - it takes the timing to nearly 3 seconds if I use that route. But this is unnecessary here, and so less worrying.

With native `reshape` and NNlib's `batched_mul` though, I get better results:

```julia
function (m::MHAttention)(x::AbstractArray{T, 3}) where {T}
    nfeatures, seq_len, batch_size = size(x)
    x_reshaped = reshape(x, nfeatures, seq_len * batch_size)
    qkv = m.qkv_layer(x_reshaped)
    qkv_reshaped = reshape(qkv, nfeatures ÷ m.nheads, m.nheads, seq_len, 3 * batch_size)
    query, key, value = chunk(qkv_reshaped, 3; dims = 4)
    scale = convert(T, sqrt(size(query, 1) / m.nheads))
    key_reshaped = reshape(permutedims(key, (2, 1, 3, 4)), seq_len, nfeatures ÷ m.nheads,
                           m.nheads * batch_size)
    query_reshaped = reshape(permutedims(query, (1, 2, 3, 4)), nfeatures ÷ m.nheads,
                             seq_len, m.nheads * batch_size)
    dots = batched_mul(query_reshaped, key_reshaped) .* scale
    attention = m.attn_drop(softmax(dots))
    value_reshaped = reshape(permutedims(value, (1, 2, 3, 4)), nfeatures ÷ m.nheads,
                             seq_len, m.nheads * batch_size)
    pre_projection = reshape(batched_mul(attention, value_reshaped),
                             (nfeatures, seq_len, batch_size))
    return m.projection(reshape(pre_projection, :, seq_len, batch_size))
end
```

gives

```julia
julia> @benchmark model($x)
BenchmarkTools.Trial: 11 samples with 1 evaluation.
 Range (min … max):  455.098 ms … 500.289 ms  ┊ GC (min … max): 2.19% … 2.72%
 Time  (median):     490.842 ms               ┊ GC (median):    2.64%
 Time  (mean ± σ):   488.968 ms ±  12.399 ms  ┊ GC (mean ± σ):  2.52% ± 0.24%

  ▁                                     ▁  ▁   ▁▁ ▁    █  ▁ ▁ ▁  
  █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁█▁▁▁██▁█▁▁▁▁█▁▁█▁█▁█ ▁
  455 ms           Histogram: frequency by time          500 ms <

 Memory estimate: 530.40 MiB, allocs estimate: 2641.
```

I checked array dimensions and they line up, meaning that the NeuralAttentionlib function still seems to be off the pace by a bit

**Comment by theabhirath** [comment]
> Wait a second, does the `MHAttention` implementation in Metalhead.jl verified? It looks a little suspicious to me...

Indeed, it uses the wrong dimensions. I'd copied it over from Lux assuming that was right, but it turns out that's a bug too. The one I've posted in the second comment on this PR is with the corrected implementation though

**Comment by chengchingwen** [comment]
> The one I've posted in the second comment on this PR is with the corrected implementation though

Which one is this?

Also, IIUC the `MHAttention` is just normal multi-head self attention, so you could actually either replace it with the one in Transformers.jl or use `NeuralAttentionlib.multihead_qkv_attention` directly after `qkv_layer`(and before `projection`).

**Comment by theabhirath** [comment]
> Which one is this?

```julia
function (m::MHAttention)(x::AbstractArray{T, 3}) where {T}
    nfeatures, seq_len, batch_size = size(x)
    x_reshaped = reshape(x, nfeatures, seq_len * batch_size)
    qkv = m.qkv_layer(x_reshaped)
    qkv_reshaped = reshape(qkv, nfeatures ÷ m.nheads, m.nheads, seq_len, 3 * batch_size)
    query, key, value = chunk(qkv_reshaped, 3; dims = 4)
    scale = convert(T, sqrt(size(query, 1) / m.nheads))
    key_reshaped = reshape(permutedims(key, (2, 1, 3, 4)), seq_len, nfeatures ÷ m.nheads,
                           m.nheads * batch_size)
    query_reshaped = reshape(permutedims(query, (1, 2, 3, 4)), nfeatures ÷ m.nheads,
                             seq_len, m.nheads * batch_size)
    dots = batched_mul(query_reshaped, key_reshaped) .* scale
    attention = m.attn_drop(softmax(dots))
    value_reshaped = reshape(permutedims(value, (1, 2, 3, 4)), nfeatures ÷ m.nheads,
                             seq_len, m.nheads * batch_size)
    pre_projection = reshape(batched_mul(attention, value_reshaped),
                             (nfeatures, seq_len, batch_size))
    return m.projection(reshape(pre_projection, :, seq_len, batch_size))
end
```

> Also, IIUC the `MHAttention` is just normal multi-head self attention, so you could actually either replace it with the one in Transformers.jl or use `NeuralAttentionlib.multihead_qkv_attention` directly after `qkv_layer`(and before `projection`).

True, this is just an experiment on my part - I eventually wanted to try and branch out the Metalhead `Layers` module into a cross of timm x xformers

**Comment by theabhirath** [comment]
> use `NeuralAttentionlib.multihead_qkv_attention` directly after `qkv_layer`(and before `projection`)

@chengchingwen So I tried this, and it's still off the pace by >100 ms.

With just NeuralAttentionlib.multihead_qkv_attention:
```julia
BenchmarkTools.Trial: 9 samples with 1 evaluation.
 Range (min … max):  580.396 ms … 592.960 ms  ┊ GC (min … max): 2.14% … 4.39%
 Time  (median):     582.015 ms               ┊ GC (median):    2.13%
 Time  (mean ± σ):   584.831 ms ±   4.778 ms  ┊ GC (mean ± σ):  2.69% ± 0.91%

  █      ▃                                                       
  █▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▇▁▁▁▁▁▁▁▁▁▇▁▁▁▁▇▁▁▁▁▁▁▁▁▁▁▁▁▁▁▇ ▁
  580 ms           Histogram: frequency by time          593 ms <

 Memory estimate: 607.98 MiB, allocs estimate: 3004.
```

With the native Metalhead version written above:

```julia
BenchmarkTools.Trial: 12 samples with 1 evaluation.
 Range (min … max):  442.011 ms … 462.986 ms  ┊ GC (min … max): 2.48% … 3.05%
 Time  (median):     448.846 ms               ┊ GC (median):    3.06%
 Time  (mean ± σ):   451.209 ms ±   7.290 ms  ┊ GC (mean ± σ):  3.21% ± 0.74%

  ▃                █                                             
  █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▇▇▁▇▁▁▁▁▇▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▇▁▁▇▇ ▁
  442 ms           Histogram: frequency by time          463 ms <

 Memory estimate: 530.40 MiB, allocs estimate: 2643.
```

**Comment by chengchingwen** [comment]
> ```julia
> function (m::MHAttention)(x::AbstractArray{T, 3}) where {T}
>     nfeatures, seq_len, batch_size = size(x)
>     x_reshaped = reshape(x, nfeatures, seq_len * batch_size)
>     qkv = m.qkv_layer(x_reshaped)
>     qkv_reshaped = reshape(qkv, nfeatures ÷ m.nheads, m.nheads, seq_len, 3 * batch_size)
>     query, key, value = chunk(qkv_reshaped, 3; dims = 4)
>     scale = convert(T, sqrt(size(query, 1) / m.nheads))
>     key_reshaped = reshape(permutedims(key, (2, 1, 3, 4)), seq_len, nfeatures ÷ m.nheads,
>                            m.nheads * batch_size)
>     query_reshaped = reshape(permutedims(query, (1, 2, 3, 4)), nfeatures ÷ m.nheads,
>                              seq_len, m.nheads * batch_size)
>     dots = batched_mul(query_reshaped, key_reshaped) .* scale
>     attention = m.attn_drop(softmax(dots))
>     value_reshaped = reshape(permutedims(value, (1, 2, 3, 4)), nfeatures ÷ m.nheads,
>                              seq_len, m.nheads * batch_size)
>     pre_projection = reshape(batched_mul(attention, value_reshaped),
>                              (nfeatures, seq_len, batch_size))
>     return m.projection(reshape(pre_projection, :, seq_len, batch_size))
> end
> ```
> 

This still not seems correct to me. The reshape/chunk/permutedims are not applied to the correct dimension. Did you compared the result with other implementations?

>  I eventually wanted to try and branch out the Metalhead Layers module into a cross of timm x xformers. Are there any optimisations in the NeuralAttentionlib implementation that might give a speed boost?

The origin of this lib is actually inspired by xformers. The goal is to provide highly modularized attention implementation with optimization for both forward/backward pass. But due to limited development time, we only have modularization part, not much optimization have been done.

**Comment by chengchingwen** [comment]
Anyway, since this PR is targeting the cpu `matmul` performance and it's already aligned with `batched_mul`, I'm going to merge this PR. 

We can continue the discussion here or on another issue.

**Pull request merged**
